apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app.kubernetes.io/instance: tseed
    app.kubernetes.io/name: frontend-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.122.247